### ISSUE TITLE
[BUG] Some WuE / BoE items in wrong categories

### ISSUE THREAD

**Issue by strayge** [AvyAddons/BetterBags_Bound#6]
### Description

Somehow some items are in wrong categories.

In plugin settings BoE, WuE and BoA categories are enabled.

BetterBags v0.3.16

### Addon Version

v1.8.0

### World of Warcraft Flavor

Retail (The War Within)

### Tested with only BetterBags_Bound

- [X] Yes

### Reproduction Steps

1. Get items
2. Open bag

### Screenshots

WuE in BoA category
<img width="345" alt="image" src="https://github.com/user-attachments/assets/ed0ef900-b2ed-459b-9700-95e005d5da6e">

WuE in Chest category
<img width="331" alt="image" src="https://github.com/user-attachments/assets/9193782d-444f-476d-a784-f74a7169db39">

BoE in Chest category
<img width="388" alt="image" src="https://github.com/user-attachments/assets/22577106-8381-42f8-b674-4b52319dab3f">

**Comment by strayge** [comment]
Seems like addon search BoA / WuE text at 2-4 lines in tooltip and for last two items it is in line 5

**Comment by strayge** [comment]
as for the first item looks like `ITEM_ACCOUNTBOUND` now translates as `Warbound`

so technically addon correctly sorted item in BoA, but maybe whole BoA should be retired,  
as all `BOA_STRINGS` now contains `warbound` / `warband` keyword in it

**Comment by lucasvienna** [comment]
> Seems like addon search BoA / WuE text at 2-4 lines in tooltip and for last two items it is in line 5

Indeed, originally this was 2-6 back in the AdiBags days, but due to performance and Tooltip scanning requiring heaps of resources, I've reduced it. Gonna put it back up to 6 and see if the performance hit isn't too bad.

> as for the first item looks like `ITEM_ACCOUNTBOUND` now translates as `Warbound`

Yes! And Warbound is the new Account Bound (stuff like Pet Charms and the Marks of Honor are now Warbound). You can always just disable it, but I don't think retiring it is the way to go here.

Another alternative would be an option to rename to "Warbound". I can make that if it's something you'd be interested in.

**Comment by strayge** [comment]
> Another alternative would be an option to rename to "Warbound".

Sounds good, not sure if it is really necessary. Also only applicable to retail, as classic do not have warbands.

Anyway thank for quick fix.
